# Generated by Django 2.2.4 on 2019-08-26 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.ImageField(default='default.jpg', max_length=300, upload_to='passports')),
                ('state', models.CharField(choices=[('1', 'Abia'), ('2', 'Adamawa'), ('3', 'Akwa-Ibom'), ('4', 'Anambra'), ('5', 'Bauchi'), ('6', 'Bayelsa')], default='1', max_length=1)),
                ('account_number', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
