# Generated by Django 2.2.4 on 2019-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.ImageField(max_length=300, upload_to='')),
                ('state', models.CharField(choices=[('1', 'Abia'), ('2', 'Adamawa'), ('3', 'Akwa-Ibom'), ('4', 'Anambra'), ('5', 'Bauchi'), ('6', 'Bayelsa')], default='1', max_length=1)),
                ('account_number', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
