# Generated by Django 2.2.4 on 2019-08-14 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=30)),
                ('project_topic', models.CharField(max_length=20)),
                ('researcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Researcher')),
            ],
        ),
    ]
