# Generated by Django 2.2.4 on 2019-08-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_file',
            field=models.FileField(default='', upload_to='uploads/'),
        ),
    ]
