# Generated by Django 2.2.4 on 2019-08-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Topic'),
        ),
    ]
