# Generated by Django 2.2.4 on 2019-08-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190815_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_image',
            field=models.ImageField(default='', max_length=200, upload_to=''),
        ),
    ]
