# Generated by Django 2.2.4 on 2019-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190820_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='passport',
            field=models.ImageField(default='default.jpg', max_length=300, upload_to='passports'),
        ),
    ]
