# Generated by Django 2.2.4 on 2019-08-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20190822_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(default='', upload_to='media/files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='related_image',
            field=models.ImageField(default='', max_length=200, upload_to='media/related_images'),
        ),
    ]
