# Generated by Django 2.2.4 on 2019-08-22 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190822_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_file',
        ),
        migrations.AddField(
            model_name='project',
            name='project_preview_file',
            field=models.FileField(default='', upload_to='media/preview_files'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
