# Generated by Django 2.2.4 on 2019-08-26 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20190822_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='state',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Researcher')),
            ],
        ),
    ]
