# Generated by Django 2.2.4 on 2019-08-26 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20190826_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='email',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='researcher',
            name='username',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
