# Generated by Django 2.2.4 on 2019-08-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20190826_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file',
            field=models.FileField(default='', upload_to='files'),
        ),
        migrations.AlterField(
            model_name='projectfile',
            name='title',
            field=models.CharField(default='Full Content', max_length=30),
        ),
    ]
