# Generated by Django 2.2.4 on 2019-09-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20190827_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_main_file',
            field=models.FileField(default='', upload_to='media/main_files'),
        ),
        migrations.DeleteModel(
            name='ProjectFile',
        ),
    ]
